import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function PrivacyPolicyMotherlyPage() {
  return (
    <>
      <Navbar />
      <main
        className=" pt-24 pb-16 md:pt-32 md:pb-20"
      // style={{ backgroundColor: "var(--color-background)" }}
      >
        <section className="max-w-5xl mx-auto px-4 sm:px-6 md:px-8">
          <div className="legal-card p-5 sm:p-7 md:p-10">
            <span className="legal-hero-chip mb-4">Privacy First</span>
            <h1
              className="text-3xl md:text-4xl font-extrabold tracking-tight mb-6"
              style={{ fontFamily: "var(--font-headline)", color: "var(--color-on-surface)" }}
            >
              MOTHERLYCARE ETHOS PRIVATE LIMITED - Privacy Policy
            </h1>

            <div className="policy-content space-y-6">
              <p>
                This Privacy Policy describes Our policies and procedures on the collection, use and
                disclosure of Your information when You use the Service and tells You about Your privacy
                rights and how the law protects You.
              </p>
              <p>
                We use Your Personal data to provide and improve the Service. By using the Service, You
                agree to the collection and use of information in accordance with this Privacy Policy.
              </p>

              <section className="space-y-3">
                <h2 className="text-2xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Interpretation and Definitions
                </h2>
                <h3 className="text-xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Interpretation
                </h3>
                <p>
                  The words whose initial letters are capitalized have meanings defined under the
                  following conditions. The following definitions shall have the same meaning regardless
                  of whether they appear in singular or in plural.
                </p>

                <h3 className="text-xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Definitions
                </h3>
                <p>For the purposes of this Privacy Policy:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                  <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                  <li><strong>Application</strong> refers to Motherly: Your Birth Companion, the software program provided by the Company.</li>
                  <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to MOTHERLYCARE ETHOS PRIVATE LIMITED, Chennai.</li>
                  <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                  <li><strong>Country</strong> refers to: Tamil Nadu, India.</li>
                  <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                  <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                  <li><strong>Service</strong> refers to the Application or the Website or both.</li>
                  <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                  <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                  <li><strong>Website</strong> refers to Motherly: Your Birth Companion, accessible from <a href="https://www.mothrly.com/" target="_blank" rel="noopener noreferrer" className="underline" style={{ color: "var(--color-primary)" }}>www.mothrly.com/</a>.</li>
                  <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
              </section>

              <section className="space-y-3">
                <h2 className="text-2xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Collecting and Using Your Personal Data
                </h2>
                <h3 className="text-xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Types of Data Collected
                </h3>
                <h4 className="text-lg font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Personal Data
                </h4>
                <p>
                  While using Our Service, We may ask You to provide Us with certain personally identifiable
                  information that can be used to contact or identify You. Personally identifiable
                  information may include, but is not limited to:
                </p>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Address, State, Province, ZIP/Postal code, City</li>
                  <li>Usage Data</li>
                </ul>

                <h4 className="text-lg font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Usage Data
                </h4>
                <p>
                  Usage Data is collected automatically when using the Service. Usage Data may include
                  information such as Your Device's Internet Protocol address (e.g. IP address), browser
                  type, browser version, the pages of our Service that You visit, the time and date of
                  Your visit, the time spent on those pages, unique device identifiers and other diagnostic
                  data.
                </p>
                <p>
                  When You access the Service by or through a mobile device, We may collect certain
                  information automatically, including, but not limited to, the type of mobile device You
                  use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile
                  operating system, the type of mobile Internet browser You use, unique device identifiers
                  and other diagnostic data.
                </p>
                <p>
                  We may also collect information that Your browser sends whenever You visit Our Service or
                  when You access the Service by or through a mobile device.
                </p>

                <h4 className="text-lg font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Information Collected while Using the Application
                </h4>
                <p>
                  While using Our Application, in order to provide features of Our Application, We may
                  collect, with Your prior permission:
                </p>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Information regarding your location</li>
                  <li>Information from your Device's phone book (contacts list)</li>
                  <li>Pictures and other information from your Device's camera and photo library</li>
                </ul>
                <p>
                  We use this information to provide features of Our Service, to improve and customize Our
                  Service. The information may be uploaded to the Company's servers and/or a Service
                  Provider's server or it may be simply stored on Your device.
                </p>
                <p>
                  You can enable or disable access to this information at any time, through Your Device
                  settings.
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-2xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Tracking Technologies and Cookies
                </h2>
                <p>
                  We use Cookies and similar tracking technologies to track the activity on Our Service and
                  store certain information. Tracking technologies We use include beacons, tags, and
                  scripts to collect and track information and to improve and analyze Our Service.
                </p>
                <p>The technologies We use may include:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                  <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
                </ul>
                <p>
                  Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your
                  personal computer or mobile device when You go offline, while Session Cookies are deleted
                  as soon as You close Your web browser. We use both Session and Persistent Cookies.
                </p>

                <h4 className="text-lg font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Necessary / Essential Cookies
                </h4>
                <p><strong>Type:</strong> Session Cookies</p>
                <p><strong>Administered by:</strong> Us</p>
                <p><strong>Purpose:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</p>

                <h4 className="text-lg font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Cookies Policy / Notice Acceptance Cookies
                </h4>
                <p><strong>Type:</strong> Persistent Cookies</p>
                <p><strong>Administered by:</strong> Us</p>
                <p><strong>Purpose:</strong> These Cookies identify if users have accepted the use of cookies on the Website.</p>

                <h4 className="text-lg font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Functionality Cookies
                </h4>
                <p><strong>Type:</strong> Persistent Cookies</p>
                <p><strong>Administered by:</strong> Us</p>
                <p><strong>Purpose:</strong> These Cookies allow us to remember choices You make when You use the Website.</p>
              </section>

              <section className="space-y-3">
                <h2 className="text-2xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Use of Your Personal Data
                </h2>
                <p>The Company may use Personal Data for the following purposes:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                  <li>To manage Your Account and Your registration as a user of the Service.</li>
                  <li>For the performance of a contract.</li>
                  <li>To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                  <li>To provide You with news, special offers, and general information unless You have opted out.</li>
                  <li>To manage Your requests to Us.</li>
                  <li>For business transfers, including merger, acquisition, or sale of assets.</li>
                  <li>For other purposes such as data analysis, trend analysis, and service improvement.</li>
                </ul>

                <p>We may share Your personal information in the following situations:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>With Service Providers.</li>
                  <li>For business transfers.</li>
                  <li>With Affiliates.</li>
                  <li>With business partners.</li>
                  <li>With other users when information is shared publicly by You.</li>
                  <li>With Your consent.</li>
                </ul>
              </section>

              <section className="space-y-3">
                <h2 className="text-2xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Retention of Your Personal Data
                </h2>
                <p>
                  The Company will retain Your Personal Data only for as long as is necessary for the
                  purposes set out in this Privacy Policy and to comply with legal obligations, resolve
                  disputes, and enforce legal agreements and policies.
                </p>
                <p>
                  The Company will also retain Usage Data for internal analysis purposes. Usage Data is
                  generally retained for a shorter period of time, except when required for security,
                  functionality improvement, or legal obligations.
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-2xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Transfer of Your Personal Data
                </h2>
                <p>
                  Your information, including Personal Data, is processed at the Company's operating offices
                  and other places where the parties involved in the processing are located. This means it
                  may be transferred to and maintained on computers outside Your jurisdiction.
                </p>
                <p>
                  Your consent to this Privacy Policy followed by Your submission of such information
                  represents Your agreement to that transfer.
                </p>
                <p>
                  The Company will take all steps reasonably necessary to ensure secure treatment of Your
                  data in accordance with this Privacy Policy.
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-2xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Delete Your Personal Data
                </h2>
                <p>
                  You have the right to delete or request that We assist in deleting the Personal Data that
                  We have collected about You.
                </p>
                <p>
                  You may update, amend, or delete Your information by signing in to Your Account and
                  visiting account settings, or by contacting Us directly.
                </p>
                <p>
                  We may retain certain information when required by law or where lawful basis exists.
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-2xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Disclosure of Your Personal Data
                </h2>
                <h3 className="text-xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Business Transactions
                </h3>
                <p>
                  If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may
                  be transferred. We will provide notice before it becomes subject to a different policy.
                </p>

                <h3 className="text-xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Law enforcement
                </h3>
                <p>
                  Under certain circumstances, the Company may be required to disclose Your Personal Data if
                  required by law or valid requests by public authorities.
                </p>

                <h3 className="text-xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Other legal requirements
                </h3>
                <p>The Company may disclose Your Personal Data to:</p>
                <ul className="list-disc pl-6 space-y-1">
                  <li>Comply with a legal obligation.</li>
                  <li>Protect and defend the rights or property of the Company.</li>
                  <li>Prevent or investigate possible wrongdoing in connection with the Service.</li>
                  <li>Protect the personal safety of Users of the Service or the public.</li>
                  <li>Protect against legal liability.</li>
                </ul>
              </section>

              <section className="space-y-3">
                <h2 className="text-2xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Security of Your Personal Data
                </h2>
                <p>
                  The security of Your Personal Data is important to Us, but no method of transmission over
                  the Internet or electronic storage is 100% secure. While We strive to use commercially
                  reasonable means, We cannot guarantee absolute security.
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-2xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Detailed Information on the Processing of Your Personal Data
                </h2>
                <p>
                  The Service Providers We use may have access to Your Personal Data. These third-party
                  vendors collect, store, use, process and transfer information about Your activity in
                  accordance with their privacy policies.
                </p>
                <h3 className="text-xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Usage, Performance and Miscellaneous
                </h3>
                <p>We may use third-party Service Providers to maintain and improve our Service.</p>
                <h4 className="text-lg font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Google Places
                </h4>
                <p>
                  Google Places is a service that returns information about places using HTTP requests. It
                  is operated by Google.
                </p>
                <p>
                  Google Places service may collect information from You and from Your Device for security
                  purposes.
                </p>
                <p>
                  The information gathered by Google Places is held in accordance with the Privacy Policy of
                  Google: <a href="https://www.google.com/intl/en/policies/privacy/" target="_blank" rel="noopener noreferrer" className="underline" style={{ color: "var(--color-primary)" }}>https://www.google.com/intl/en/policies/privacy/</a>
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-2xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Children's Privacy
                </h2>
                <p>
                  Our Service does not address anyone under the age of 13. We do not knowingly collect
                  personally identifiable information from anyone under 13.
                </p>
                <p>
                  If You are a parent or guardian and believe Your child has provided Us with Personal Data,
                  please contact Us. If We become aware that We have collected Personal Data from anyone
                  under 13 without parental consent verification, We take steps to remove that information.
                </p>
                <p>
                  If We rely on consent as legal basis and Your country requires parental consent, We may
                  require a parent's consent before collection and use.
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-2xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Links to Other Websites
                </h2>
                <p>
                  Our Service may contain links to other websites that are not operated by Us. If You click
                  on a third party link, You will be directed to that third party's site. We strongly
                  advise You to review the Privacy Policy of every site You visit.
                </p>
                <p>
                  We have no control over and assume no responsibility for the content, privacy policies or
                  practices of any third party sites or services.
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-2xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Changes to this Privacy Policy
                </h2>
                <p>
                  We may update Our Privacy Policy from time to time. We will notify You of any changes by
                  posting the new Privacy Policy on this page.
                </p>
                <p>
                  We will let You know via email and/or a prominent notice on Our Service, prior to the
                  change becoming effective and update the "Last updated" date at the top of this Privacy
                  Policy.
                </p>
                <p>
                  You are advised to review this Privacy Policy periodically for any changes. Changes are
                  effective when posted on this page.
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-2xl font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                  Contact Us
                </h2>
                <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                <div className="rounded-2xl p-4 md:p-6" style={{ backgroundColor: "var(--color-surface-container-low)" }}>
                  <p className="font-bold" style={{ color: "var(--color-on-surface)", fontFamily: "var(--font-headline)" }}>
                    MOTHERLYCARE ETHOS PRIVATE LIMITED
                  </p>
                  <p>3rd Floor, Alpha Block, SSPDL Alphacity, 301-B3,</p>
                  <p>Rajiv Gandhi Salai, Navalur, Chennai, Tamil Nadu 600130</p>
                  <p>
                    By email: <a href="mailto:motherlycareethos@gmail.com" className="underline" style={{ color: "var(--color-primary)" }}>motherlycareethos@gmail.com</a>
                  </p>
                  <p>
                    By Phone: <a href="tel:+919944890577" className="underline" style={{ color: "var(--color-primary)" }}>+91 99448 90577</a>
                  </p>
                </div>
              </section>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
